-- MySQL Script generated by MySQL Workbench
-- Thu Jul 22 12:20:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projeto_integrador
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_integrador
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_integrador` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `projeto_integrador` ;

-- -----------------------------------------------------
-- Table `projeto_integrador`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`tb_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`tb_tema` (
  `id_tema` INT NOT NULL AUTO_INCREMENT,
  `nome_tema` VARCHAR(255) NULL DEFAULT NULL,
  `categoria` VARCHAR(255) NULL DEFAULT NULL,
  `sub_categoria` VARCHAR(255) NULL,
  PRIMARY KEY (`id_tema`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `projeto_integrador`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_integrador`.`tb_postagem` (
  `id_postagem` INT NOT NULL AUTO_INCREMENT,
  `midia` VARCHAR(255) NULL DEFAULT NULL,
  `comentarios` VARCHAR(255) NULL DEFAULT NULL,
  `titulo` VARCHAR(255) NULL DEFAULT NULL,
  `publicacao` VARCHAR(255) NULL DEFAULT NULL,
  `fk_usuario` INT NULL DEFAULT NULL,
  `fk_tema` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_postagem`),
  INDEX `fk_usuario` (`fk_usuario` ASC) VISIBLE,
  INDEX `fk_tema` (`fk_tema` ASC) VISIBLE,
  CONSTRAINT `tb_postagem_ibfk_1`
    FOREIGN KEY (`fk_usuario`)
    REFERENCES `projeto_integrador`.`tb_usuario` (`id_usuario`),
  CONSTRAINT `tb_postagem_ibfk_2`
    FOREIGN KEY (`fk_tema`)
    REFERENCES `projeto_integrador`.`tb_tema` (`id_tema`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
